---
- hosts: dev
  become: true
  tasks:
      - name: installing docker
        yum:
          name: docker
          state: present

      - name: starting docker service
        service:
            name: docker
            state: started
            enabled: yes

      - name: stopping container
        shell: docker stop  myfirstappcont

      - name: removing docker conatiner
        shell: docker rm myfirstappcont

      - name: removing the docker image
        shell: docker rmi atul1325/myfirstapp
    
      - name: creating a new docker conatiner
        shell: docker run -itd --name myfirstappcont -p 8080:8080 atul1325/myfirstapp
